import Head from "next/head"
import styles from "../../styles/Home.module.css"
import { Recipe } from "../../types/recipe"
import Image from "next/image"
import { getAllRecipes, getRecipe } from "../../lib/recipes"
import { IngredientBox } from "../../components/IngredientBox"
import { DirectionBox } from "../../components/DirectionBox"

interface Props {
  recipe: Recipe
}

const Recipe = ({ recipe }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{`CookBook | ${recipe.title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {recipe.imageUrl && (
          <Image
            src={recipe.imageUrl}
            alt={`Image of ${recipe.title}`}
            width={200}
            height={200}
          />
        )}
        <h1 className={styles.title}>{recipe.title}</h1>
        <IngredientBox ingredients={recipe.ingredients} />
        <DirectionBox directions={recipe.directions} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Recipe

type Params = {
  params: {
    key: string
  }
}

export const getStaticProps = async ({ params }: Params) => {
  const recipe: Recipe = getRecipe(params.key)
  return {
    props: {
      recipe: recipe,
    },
  }
}

export async function getStaticPaths() {
  const recipes: Array<Recipe> = getAllRecipes()
  return {
    paths: recipes.map((recipe) => {
      return {
        params: {
          key: recipe.key,
        },
      }
    }),
    fallback: false,
  }
}
