import Head from "next/head"
import styles from "../../styles/Home.module.css"
import { RecipeType } from "../../types/recipe"
import { getAllRecipes, getRecipeBySlug } from "../../lib/recipes"

interface Props {
  title: string
}

const Recipe = ({ title }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CookBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Recipe

type Params = {
  params: {
    slug: string
  }
}

export const getStaticProps = async ({ params }: Params) => {
  const recipe: RecipeType = getRecipeBySlug(params.slug, ["title"])
  return {
    props: { title: recipe.title },
  }
}

export async function getStaticPaths() {
  const recipes: Array<RecipeType> = getAllRecipes(["slug"])
  return {
    paths: recipes.map((recipe) => {
      return {
        params: {
          slug: recipe.slug,
        },
      }
    }),
    fallback: false,
  }
}
