import Head from "next/head"
import styles from "../styles/Home.module.css"
import { Recipe } from "../types/recipe"
import { getAllRecipes } from "../lib/recipes"
import RecipeItem from "../components/RecipeItem"

export const getStaticProps = async () => {
  const recipes: Array<Recipe> = getAllRecipes()
  return {
    props: { recipes },
  }
}

interface Props {
  recipes: Array<Recipe>
}

const Home = ({ recipes }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CookBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CookBook</h1>

        <p className={styles.description}>Awesome recipes follow</p>

        <ul>
          {recipes.map((recipe) => (
            <RecipeItem
              key={recipe.key}
              name={recipe.key}
              title={recipe.title}
            />
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
